### ISSUE TITLE
Attempting to add a new user causes TypeError: no implicit conversion of Array into String

### ISSUE THREAD

**Issue by luismadrigal** [ruby-ldap/ruby-net-ldap#193]
Some details first:
Ruby 2.2.0
Rails 4.2.0
Gem version 0.11

When I try to run this code from my rails app I get a "TypeError: no implicit conversion of Array into String"

    def add_user
        ldap = Net::LDAP.new host: @host, port: @port , auth: @creds
      dn = "cn=Test User,ou=people,dc=<my dc list here>"
      user = {
          objectclass: ['top','posixAccount','person','inetOrgPerson','organizationalPerson','inetUser'],
          uid: "tuser",
          cn: "Test User",
          givenName: "Test",
          sn: "User",
          uidNumber: 0,
          gidNumber: 9999,
          homeDirectory: "/home/tuser",
          loginShell: "/bin/bash",
          mail: "tuser@example.com",
          userPassword: "test"
        }
       ldap.add( dn: dn, attributes: user )
    end

Here is part of the stack trace:

    TypeError: no implicit conversion of Array into String
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/net-ldap- 0.11/lib/net/ldap/connection.rb:13:in `initialize'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/net-ldap-0.11/lib/net/ldap/connection.rb:13:in `new'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/net-ldap-0.11/lib/net/ldap/connection.rb:13:in `initialize'
	from /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/net-ldap-0.11/lib/net/ldap.rb:1223:in `new'

What am I not seeing?

**Comment by luismadrigal** [comment]
This is kind of weird issue, it should be noted somewhere, but it turns out that all the attributes need to be  pass as strings i.e. in quotes.  I was passing numbers not quoted, so that was the problem.
