### ISSUE TITLE
undefined method `map' for 18400597803079440689678002902069631524796887079072566:Bignum (NoMethodError)

### ISSUE THREAD

**Issue by aktis-info** [ruby-ldap/ruby-net-ldap#91]
In attempt of execution of a code:

```
require 'pry'
require 'net/ldap'
$HOST =    'psp.int'
$PORT =    389

auth = {
  :method => :simple, 
  :username => 'psp\\administrator', 
  :password => 'Aa123456'
}
ldap = Net::LDAP.new(:host => $HOST, :port => $PORT, :auth => auth)
ldap.open do |ldap|
  treebase = "ou=Offices, dc=psp, dc=int"

  dn = "cn=George Smith, #{treebase}"
  attr = {
    :cn => "George Smith",

    :samAccountName => 'gs',
    :userPrincipalName => 'gs@psp.int',
    :useraccountcontrol => 0x0200,
    :pwdLastSet => 0,

    :objectclass => ['top',"person", "organizationalPerson", "user"],
    :sn => "Smith",
    :mail => "gsmith@example.com"
  }
  ldap.add(:dn => dn, :attributes => attr)
end
```

There is the following error:

```
/var/lib/gems/1.9.1/gems/net-ldap-0.6.1/lib/net/ldap/pdu.rb:219:in `parse_controls': undefined method `map' for 18400597803079440689678002902069631524796887079072566:Bignum (NoMethodError)
        from /var/lib/gems/1.9.1/gems/net-ldap-0.6.1/lib/net/ldap/pdu.rb:104:in `initialize'
        from /var/lib/gems/1.9.1/gems/net-ldap-0.6.1/lib/net/ldap.rb:1603:in `new'
        from /var/lib/gems/1.9.1/gems/net-ldap-0.6.1/lib/net/ldap.rb:1603:in `add'
        from /var/lib/gems/1.9.1/gems/net-ldap-0.6.1/lib/net/ldap.rb:830:in `add'
        from ldap_exp_net_ldap.rb:36:in `block in <main>'
        from /var/lib/gems/1.9.1/gems/net-ldap-0.6.1/lib/net/ldap.rb:580:in `open'
        from ldap_exp_net_ldap.rb:12:in `<main>'
```

ActiveDirectory level 2003
The code is taken from an example http://net-ldap.rubyforge.org/Net/LDAP.html#method-i-add
Search takes place successfully

**Comment by Poohblah** [comment]
@schaary: any possibility we could get the net-ldap library to spit out a more friendly error message instead of "undefined method map for Bignum"? Perhaps something like "Expected String, received Int"?
